power <- read.csv("household_power_consumption.txt", sep=";")
s <- subset(power, power$Date == '2/1/2007' | power$Date == '2/2/2007')
sm1 <- as.numeric(as.character(s$Sub_metering_1))
sm2 <- as.numeric(as.character(s$Sub_metering_2))
sm3 <- as.numeric(as.character(s$Sub_metering_3))
png(filename="plot3.png",width=480,height=480)
plot(dt, sm1, type='l', ylim=c(0,35))
lines(dt, sm2, type='l', col="red")
lines(dt, sm3, type='l', col="blue")
legend("topright", legend=c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lty=c(1,1,1), lwd=c(2.5, 2.5, 2.5), col=c("black", "red", "blue"))
